const errorMessages = {
  ERROR_GETTING_DATA_FROM_DB: "ERROR_GETTING_DATA_FROM_DB",
  INVALID_TOKEN: "INVALID_TOKEN",
  ERROR_CONNECTING_DATABASE: "ERROR_CONNECTING_DATABASE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  NOT_FOUND: "NOT_FOUND",
  INVALID_QR_CODE: "INVALID_QR_CODE",
  QR_CODE_EXPIRED: "QR_CODE_EXPIRED",
  INVALID_AMOUNT: "Amount must be greater than 0",
  DRIVER_DEACTIVATED: "DRIVER_DEACTIVATED",
  UNDER_MAINTENANCE: "UNDER_MAINTENANCE",
  TOKEN_NOT_PROVIDED: "TOKEN_NOT_PROVIDED",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  CHARGING_STATION_IS_CURRENTLY_BLOCKED:
    "CHARGING_STATION_IS_CURRENTLY_BLOCKED",
};

export default errorMessages;
