export enum COUNTRY {
    UNITED_ARAB_EMIRATES = 1,
    SAUDI_ARABIA = 2,
    UNITED_STATES = 3,
    SINGAPORE = 4,
    THAILAND = 5,
    QATAR = 6,
    KUWAIT = 7,
    UNITED_KINGDOM = 8,
    MALAYSIA = 9,
    CANADA = 10,
    AUSTRALIA = 11,
    CHINA = 12,
    NEPAL = 13,
    SRI_LANKA = 14,
    OMAN = 15,
    INDONESIA = 16,
    BAHRAIN = 17,
    GERMANY = 18,
    FRANCE = 19,
    SOUTH_AFRICA = 20,
    ITALY = 21,
    NEW_ZEALAND = 22,
    SWITZERLAND = 23,
    JAPAN = 24,
    SOUTH_KOREA = 25,
    PHILIPPINES = 26,
    BANGLADESH = 27,
    RUSSIA = 28,
    EGYPT = 29,
    MAURITIUS = 30,
    MALDIVES = 31,
    NETHERLANDS = 32,
    SPAIN = 33,
    TURKEY = 34,
    VIETNAM = 35,
    GREECE = 36,
    HONG_KONG = 37,
    BRAZIL = 38,
    MEXICO = 39,
    SWEDEN = 40,
    NORWAY = 41,
    DENMARK = 42,
    BELGIUM = 43,
    AUSTRIA = 44,
    FINLAND = 45,
    IRELAND = 46,
    POLAND = 47,
    PORTUGAL = 48,
    CZECH_REPUBLIC = 49,
    HUNGARY = 50,
    INDIA = 51,
  }

  export enum STATE {
    // Indian States
    ANDHRA_PRADESH = 1,
    ARUNACHAL_PRADESH = 2,
    ASSAM = 3,
    BIHAR = 4,
    CHHATTISGARH = 5,
    GOA = 6,
    GUJARAT = 7,
    HARYANA = 8,
    HIMACHAL_PRADESH = 9,
    JHARKHAND = 10,
    KARNATAKA = 11,
    KERALA = 12,
    MADHYA_PRADESH = 13,
    MAHARASHTRA = 14,
    MANIPUR = 15,
    MEGHALAYA = 16,
    MIZORAM = 17,
    NAGALAND = 18,
    ODISHA = 19,
    PUNJAB = 20,
    RAJASTHAN = 21,
    SIKKIM = 22,
    TAMIL_NADU = 23,
    TELANGANA = 24,
    TRIPURA = 25,
    UTTAR_PRADESH = 26,
    UTTARAKHAND = 27,
    WEST_BENGAL = 28,
    
    // Union Territories
    ANDAMAN_AND_NICOBAR_ISLANDS = 29,
    CHANDIGARH = 30,
    DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU = 31,
    DELHI = 32,
    JAMMU_AND_KASHMIR = 33,
    LADAKH = 34,
    LAKSHADWEEP = 35,
    PUDUCHERRY = 36,
    
    // Major US States (adding just a few for example)
    CALIFORNIA = 37,
    NEW_YORK = 38,
    TEXAS = 39,
    FLORIDA = 40,
    
    // Major UK regions
    ENGLAND = 41,
    SCOTLAND = 42,
    WALES = 43,
    NORTHERN_IRELAND = 44,
    
    // Major Canadian provinces
    ONTARIO = 45,
    QUEBEC = 46,
    BRITISH_COLUMBIA = 47,
    
    // Major Australian states
    NEW_SOUTH_WALES = 48,
    VICTORIA = 49,
    QUEENSLAND = 50
  }